import type { Metadata } from 'next';
import { SITE_NAME } from './constants';

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://www.offreiptv.com';

export interface PageMetadataInput {
  title: string;
  description: string;
  path: string;
  /** Custom OG image path (e.g. article cover). Omit to use the site-wide default generated by app/opengraph-image.tsx. */
  ogImage?: string;
  type?: 'website' | 'article';
}

export function buildMetadata({
  title,
  description,
  path,
  ogImage,
  type = 'website',
}: PageMetadataInput): Metadata {
  const canonical = `${siteUrl}${path}`;
  const fullTitle = title.includes(SITE_NAME) ? title : `${title} | ${SITE_NAME}`;

  const ogImages = ogImage
    ? [{ url: `${siteUrl}${ogImage}`, width: 1200, height: 630, alt: title }]
    : [{ url: `${siteUrl}/opengraph-image`, width: 1200, height: 630, alt: title }];

  return {
    title,
    description,
    alternates: {
      canonical,
    },
    openGraph: {
      title: fullTitle,
      description,
      url: canonical,
      siteName: SITE_NAME,
      locale: 'fr_FR',
      type,
      images: ogImages,
    },
    twitter: {
      card: 'summary_large_image',
      site: '@offreiptv',
      title: fullTitle,
      description,
      images: [ogImages[0].url],
    },
  };
}

export function getSiteUrl(): string {
  return siteUrl;
}
